### ISSUE TITLE
Collection has been modified while accessing it

### ISSUE THREAD

**Issue by dtflx01** [gnatmq/gnatmq#13]
When subscribing to several messages while publishing default values to these messages from the main thread, I get exceptions in MqttSubscriberManager.cs and MqttSubscriberManager.cs saying that the collection has been modified while accessing it.
The correction I applied is, the subscribers and retainedMessages collection have to be sourrounded by lock statements with the collections implied.
Regards

**Comment by PinkyPonky** [comment]
I can confirm it too: I noticed that for example Subscribe and Unsubscribe() have lock(this.subscribers) statement present, but not GetSubscriptions(..).

I have surrounded missing functions with lock (this.subscribers) {} and it solves the issue.

**Comment by PinkyPonky** [comment]
Reporting another instance as in MqttBroker.cs: 470, line:
"return query.FirstOrDefault()"
throws 'Collection was modified; enumeration operation may not execute.'
Until now, i was unable to reproduce the exeption.

**Comment by dtflx01** [comment]
@VladimirAkopyan , can you reopen this issue, because it's not completely corrected.
It's linked to pull request #52.
Thank you.

**Comment by dtflx01** [comment]
@VladimirAkopyan , the fix is in this commit a052978.
I didn't succed in making a new pull request from my fork.
Can you merge this commit please ?
Regards
