### ISSUE TITLE
Problems With SSL and Windows 10 IoT Core

### ISSUE THREAD

**Issue by toran73** [gnatmq/gnatmq#30]
Hello! 

I actually left this as a reply to Paolos [Article..](https://paolopatierno.wordpress.com/2015/08/17/windows-iot-core-and-m2mqtt-a-simple-marriage/) regarding using M2Mqtt for Windows 10 IoT Core. but I thought maybe this could be interesting for more people so I will ask this question here also..

Im currently building a "Local Agent" for an Central IoT Solution using Raspberry and Windows 10 IoT Core. We already have a Mqtt Broker set up and it works great for several different clients including, iOS, Windows and ESP8266. To handle basic security we use SSL (TLS1.2 Protocol) with a bought certificate from a trusted certificate authority.

Now Im trying to use M2Mqtt for Mqtt Client and it looks like it connects ok, but I cant get it to publish or notify me on any subscribed topics… No exceptions... no nothing.. just cant get any events to fire or publish anything to my topics…:/

Right now I’m using the version from NuGet, but I think I need to get the code to debug this further…

What do you think? have you tested this client on IoT Core using SSL?

Best regards
Torbjörn Nilsson

**Comment by VladimirAkopyan** [comment]
I don't think this works on Iot Core using SSL. Generally local deployments with SSL are very troublesome. One of the problems is that the SSL needs to be kept secret, and you could just pull out SD card and read it. 
However .net core and kestrel work fine with SSL, so you could go for linux on raspberri pi and .net core

**Comment by toran73** [comment]
Vladimir!

Of course this is a issue but THAT problem exist independently on what platform you use.. If you control the client you might have the possibility to use the certificate, and using it will get you TO the servern but not IN to it! There is several levels of Authentication and Authorization to keep Any client from actually doing anything in the system.

But you might be right that its not supported (even though it looks like it), I would really like someone to verify that there is a problem or tell me that it works for them, that would be helpfull :)

**Comment by toran73** [comment]
Sorry! 

I see now that I published this Issue on GnattMq.. I thought this was the M2Mqtt Repo! I Will move it there!..

Again, I'm sorry for the confusion!
