### ISSUE TITLE
Problems with Xamarin Studio

### ISSUE THREAD

**Issue by allussa** [gnatmq/gnatmq#34]
I have a problem with the connection MqttClient:

public void Connect(string server)
{
	 try
		 {
			 client = new MqttClient(server);
			 string clientId = Guid.NewGuid().ToString();
			 client.Connect(clientId);
			 Broker = server;
		 }
		 catch (Exception ex)
		 {
		 	 throw new Exception(ex.Message);
		 }
}

Error CS0012: The type `System.Net.IPAddress' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System, Version=3.9.0.0, Culture=neutral, PublicKeyToken=969db8053d3322ac, Retargetable=Yes' (CS0012)

Can You help me, please?

Toni

**Comment by dkkriste** [comment]
Are you trying to run a mqtt broker on a phone?
Or are you looking for the mqtt client: https://github.com/eclipse/paho.mqtt.m2mqtt

**Comment by allussa** [comment]
I would like put an client and broker in the same application with xamarin forms.

It's possible?

Thanks.

**Comment by dkkriste** [comment]
That should be possible, though you will probably run into a namespace conflict and have to duplicate client and broker code and give one of them a different namespace.
However, i must ask, why do you wish to run a broker on the device?
