### ISSUE TITLE
MqttBroker hangs

### ISSUE THREAD

**Issue by borigas** [gnatmq/gnatmq#36]
Twice after running for about a week, I've had `MqttBroker` not respond when a client attempts to connect. Once this has happened, if I try to call `_mqttBroker.Stop()`, to gracefully shutdown, it hangs. I end up having to kill the process to restart. Does anyone have any ideas what might be causing this? I'm happy to try to help fix it, but don't know where to start. If there's any more info I can provide, please let me know

**Comment by dtflx01** [comment]
Hi Borigas,

You can take a look at some kind of equivalent problem I had to face to.
See issues #13 and #32 :
[https://github.com/ppatierno/gnatmq/issues/32](url)
[https://github.com/ppatierno/gnatmq/issues/13](url)

Hoping it would help.
Regards

**Comment by nkostis** [comment]
i think this is a different problem. After accept()ing a new client the code does not switch to a new thread to handle the connection, SSL handshake etc. If for any reason this hands then the broker continues but will no longer accept() anything until restarted.
I solved this by partitioning the connection acceptance and handling into a new task (use try/catch!) and immediately returning the main thread to accept().

**Comment by borigas** [comment]
Thanks @dtflx01. I think I've seen #13 happen, but like @nkostis said, I think this might be something different.

@nkostis, that definitely sounds like it could be the cause of what I'm seeing. Is your code for that available anywhere? I hate to reinvent the wheel

**Comment by nkostis** [comment]
GitHub won't let me post a patch here so i will paste the code 
(GnatMQ/Net/MqttTcpCommunicationLayer.cs / method: private void ListenerThread())

`    try
    {
        // blocking call to wait for client connection
        Socket socketClient = this.listener.AcceptSocket();

        // manage socket client connected
        if (socketClient.Connected)
        {
            var tThisConn = new Thread(() =>
            {
                try
                {
                    // create network channel to accept connection request
                    IMqttNetworkChannel channel = null;
#if SSL
                    if (this.Secure)
                    {
#if !(MF_FRAMEWORK_VERSION_V4_2 || MF_FRAMEWORK_VERSION_V4_3 || COMPACT_FRAMEWORK)
                        channel = new MqttNetworkChannel(socketClient, this.Secure, this.ServerCert, this.Protocol, this.UserCertificateValidationCallback, this.UserCertificateSelectionCallback);
#else
                        channel = new MqttNetworkChannel(socketClient, this.Secure, this.ServerCert, this.Protocol);
#endif
                    }
                    else
                    {
                        channel = new MqttNetworkChannel(socketClient);
                    }
#else
                    channel = new MqttNetworkChannel(socketClient);
#endif
                    channel.Accept();

                    // handling channel for connected client
                    MqttClient client = new MqttClient(channel);

                    // raise client raw connection event
                    this.OnClientConnected(client);
                }
                catch { }
            });

            //add this connection to ongoing ones
            OngoingConnections.Add(tThisConn.ManagedThreadId, new TupleS<Thread, DateTime>(tThisConn, DateTime.UtcNow));

            //start the connection
            tThisConn.Start();
        }
    }
    catch (Exception)
    {
        if (!this.isRunning)
            return;
    }
`

The only difference from upstream code is that the upstream connection handling is place into the tThisConn thread. You will see it's also added into a tracking dictionary, so that a background bookkeeping thread can track the ongoing connections and kill the stale ones.

This is good practice in general so it wouldn't be a bad idea if @ppatierno included this in upstream.

**Comment by borigas** [comment]
Thanks @nkostis! I'm hoping to test this some soon. Hopefully I can prove that this fixes the same problem I've been having

**Comment by borigas** [comment]
I've been unable to reliably reproduce my initial problem, so I can't prove that this fixes it, but it sure seems like it should. Thanks for your help @nkostis!

**Comment by borigas** [comment]
I was able to reproduce the problem by connecting a client without TLS to the broker with TLS. It never finishes accepting the connection so it won't accept new socket connections or exit the app. @nkostis fix above worked great. Thanks @nkostis! I also updated `MqttNetworkChannel.Accept()` with a timeout so `AuthenticateAsServer()` doesn't hang anymore
```
        public void Accept()
        {
#if SSL
            // secure channel requested
            if (secure)
            {
#if !(MF_FRAMEWORK_VERSION_V4_2 || MF_FRAMEWORK_VERSION_V4_3)

                this.netStream = new NetworkStream(this.socket);
                this.sslStream = new SslStream(this.netStream, false, this.userCertificateValidationCallback, this.userCertificateSelectionCallback);

                // Allow timeout to occur 
                this.sslStream.ReadTimeout = MqttSettings.MQTT_CONNECT_TIMEOUT;
                this.sslStream.WriteTimeout = MqttSettings.MQTT_CONNECT_TIMEOUT;

                this.sslStream.AuthenticateAsServer(this.serverCert, false, MqttSslUtility.ToSslPlatformEnum(this.sslProtocol), false);

                this.sslStream.ReadTimeout = System.Threading.Timeout.Infinite;
                this.sslStream.WriteTimeout = System.Threading.Timeout.Infinite;
#endif
            }

            return;
#else
            return;
#endif
        }
```
