### ISSUE TITLE
NullReferenceException in MqttClient - MQTT broker to MQTT client communication

### ISSUE THREAD

**Issue by chkr1011** [gnatmq/gnatmq#38]
Hi,
I use the Broker on my Raspberry Pi running Windows 10 IoT Core. Due to the network isolation, it is not possible to run the broker and the client at the same machine connecting via a loopback connection. So I decided to implement the communication layer and build an in-memory connection which allows connecting regular clients via TCP and inside my application via RAM. The broker runs without a problem but the MqttClient is not usable.

The ctor I use is: ```public MqttClient(IMqttNetworkChannel channel)```

Whenever I call _Connect("MyClient")_  I get a _NullReferenceException_. StackTrace:

```c#
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(Byte[] msgBytes, Int32 timeout)
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(MqttMsgBase msg, Int32 timeout)
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(MqttMsgBase msg)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId)
   at HA4IoT.Hardware.Mqtt.MqttService.Startup()
   at HA4IoT.Core.ContainerExtensions.StartupServices(Container container)
```

Whithout calling _Connect("MyClient")_ I can still send messages without problems.

I forked this project and saw that the object which is _null_ is: `this.syncEndReceiving.Reset(); // at line 1053`

I tried to solve the problem on my own via adding this following line to the contructor: ```this.syncEndReceiving = new AutoResetEvent(false);```

Then I get no _NullReferenceException_ anymore but after a certain time (a few seconds) I always get a _MqttCommunicationException_. It seems that the timeout of the _AutoResetEvent_ is not _Set()_ properly to the _WaitOne()_ method returns false.

My implementations of the communication channel are (maybe these are causing the issue):

```c#
public class MqttBrokerChannel : IMqttCommunicationLayer
    {
        private readonly StreamSocketListener _socket = new StreamSocketListener();

        public event MqttClientConnectedEventHandler ClientConnected;

        public void Start()
        {
            _socket.ConnectionReceived += ProcessConnection;
            _socket.BindServiceNameAsync(MqttSettings.Instance.Port.ToString()).AsTask().Wait();

            Log.Info($"Started MQTT broker with port {MqttSettings.Instance.Port}.");
        }

        public void Stop()
        {
            _socket.Dispose();
        }

        public void Attach(MqttClient mqttClient)
        {
            if (mqttClient == null) throw new ArgumentNullException(nameof(mqttClient));

            Log.Verbose("Attached internal client to MQTT broker.");
            ClientConnected?.Invoke(this, new MqttClientConnectedEventArgs(mqttClient));
        }

        private void ProcessConnection(StreamSocketListener sender, StreamSocketListenerConnectionReceivedEventArgs args)
        {
            Log.Verbose($"External client ({args.Socket.Information.RemoteAddress}) connected to MQTT broker.");
            var mqttClient = new MqttClient(new MqttNetworkChannel(args.Socket));
            ClientConnected?.Invoke(this, new MqttClientConnectedEventArgs(mqttClient));
        }
    }

    public class MqttLoopbackClientChannel : IMqttNetworkChannel
    {
        private readonly object _syncRoot = new object();
        private readonly ManualResetEvent _memoryGate = new ManualResetEvent(false);
        private readonly MemoryStream _memory = new MemoryStream();

        public bool DataAvailable
        {
            get
            {
                lock (_syncRoot)
                {
                    return _memory.Length > 0;
                }
            }
        }

        public int Receive(byte[] buffer)
        {
            return Receive(buffer, Timeout.Infinite);
        }

        public int Receive(byte[] buffer, int timeout)
        {
            if (!_memoryGate.WaitOne(timeout))
            {
                return 0;
            }

            lock (_syncRoot)
            {
                var length = _memory.Read(buffer, 0, buffer.Length);

                if (_memory.Position == _memory.Length)
                {
                    _memory.SetLength(0);
                    _memoryGate.Reset();
                }

                return length;
            }
        }

        public int Send(byte[] buffer)
        {
            lock (_syncRoot)
            {
                _memory.Write(buffer, 0, buffer.Length);
                _memory.Position -= buffer.Length;

                _memoryGate.Set();
                return buffer.Length;
            }
        }

        public void Close() { }

        public void Connect() { }

        public void Accept() { }
    }
```

Best regards,
Christian Kratky

**Comment by chkr1011** [comment]
Update:

Now it works. The memory stream had some bugs and I figured out that the _GnatMQ_ `MqttClient` cannot be used as a MQTT _Client_. So I need to include the _M2MQTT_ library as well.

But I have to fight namespace clashes because everything seems to have the name!? It is possible to use a different namespace for GnatMQ @ppatierno? Otherwise I need to add a library an create a wrapper for the M2MQTT client stuff or use an _alias_ for the assembly which does not work with _Unversal Windows_ references from nuget.

To get it running I also need to change the code of the M2MQTT `MqttClient`. But I will create a pull request at the other respository.

Best regards
Christian

**Comment by dtflx01** [comment]
I confirme that I had the same issue using MQTT Client from GnatMQ library. I used instead M2MQTT as client. This implies modifying namespaces to avoid conflicts.
Regards

**Comment by trbenning** [comment]
@chkr1011 You can work around the namespace clash by using external aliases. 

Select the `GnatMQ.Net` project references and, in the properties window, change the value of `Aliases` from `global` to something else like `GnatMQ`. Then, in your namespace imports, type `extern alias GnatMQ`, and from there you can reference the Gnat types like this: 

`GnatMQ::uPLibrary.Networking.M2Mqtt.MqttClient`.

**Comment by VladimirAkopyan** [comment]
Documenting all attempts to accomplish integration withing one application #47

**Comment by dtflx01** [comment]
Dear All,
I've the feature done locally, but it will lose compatibility with previous implementation.
This imply to change namespace names to have Gnatmq working with M2mqtt library on the same project.
What is your opinion ?

**Comment by VladimirAkopyan** [comment]
@dtflx01 I have two thoughts on the matter:
1. Having the same name on both assemblies is not sensible
2. I think that having a direct API / interface might be a better way to accomplish this than emulating a network connection. - it would be simpler to use. I tried to document one such attempt in #47 . Are there use-cases where having such API would not be appropriate or sufficient?

**Comment by dtflx01** [comment]
@VladimirAkopyan   your are right, but it would be some work to do a such API.

**Comment by VladimirAkopyan** [comment]
@dtflx01 I was thinking how we could add testin, and it seems like your work could help with that.

**Comment by dtflx01** [comment]
@VladimirAkopyan fortunately I share my local work to the community trying to stabilize the GnatMQ library , but unfortunately it's out of my work to enhance the library except enhancements I've done for my work.
I'll continu helping the community as well as little :-)
Thank you for your help Vladimir.
Best regards

**Comment by VladimirAkopyan** [comment]
@dtflx01  Ofc. and thanks a lot for your contributions - I am just asking for opinion atm. 
 We need to get it to the point where it's a reliable library, not just a toy. 
Are you using it on .Net Compact?

**Comment by dtflx01** [comment]
@VladimirAkopyan, this is my thoughts,
I'm using GnatMQ for now more than one year on our industrial products (still in test). It's not far away beeing stable.
It remains some corrections to publish I've got locally.
Yes I'm using it on .Net Compact 2013 such as M2Mqtt library for client. The same library is also working on Windows 10.
I'm using M2Mqtt and GnatMQ on the same OS Windows CE. It'd be great to have a virtual client on GnatMQ.
