### ISSUE TITLE
Bug in subscription matching

### ISSUE THREAD

**Issue by DennisSc** [gnatmq/gnatmq#42]
Hi,
I've encountered an issue with GnatMQ where a client receives messages that he hasn't subscribed to.

The issue is that the client subscribes to "some/topic" only (no wildcard), but as result also receives "some/topic/sub" messages. This is very unlucky if the client uses several subtopics for different tasks...
With other brokers (and the same, proven and working MQTT clients), everything works fine.
When replacing mosquitto with GnatMQ as the broker (in a running configuration of various clients), the issue has been observed, but you can also reproduce it in an isolated environment (tested on both Win10 IoT Core and Win10 x64).

Steps to reproduce:

- start "vanilla" GnatMQ broker, in either UAP or win32 console application
- using the "mosquitto_sub" tool, subscribe to "some/topic":
`mosquitto_sub -h 192.168.1.111 -t "some/topic" -v`
- then publish using "mosquitto_pub":
`mosquitto_pub -h 192.168..1.111 -t "some/topic/bla"  -d `-l`
`0`

expected behavior: message isn't sent to client, since he didnt' subscribe to any wildcard and has no exactly matching subscription.

observed behavior: message is sent to client nevertheless:
`some/topic/bla 0`

(also reproducible with M2Mqtt client)

I suspect "this regex stuff" in MqttSubscriberManager.cs to be responsible, but have no clue what to do to fix it. When I should test something just let me know.

regards

EDIT:
wow I'm learning regex in c# ... :)

I've probably found the cause. I tried the following:
`

            string string1 = "some/topic";
            string PLUS_WILDCARD = "+";
            string SHARP_WILDCARD = "#";

            string PLUS_WILDCARD_REPLACE = @"[^/]+";
            string SHARP_WILDCARD_REPLACE = @".*";

            string string2 = string1.Replace(PLUS_WILDCARD, PLUS_WILDCARD_REPLACE).Replace(SHARP_WILDCARD, SHARP_WILDCARD_REPLACE);
            Console.WriteLine("replaced topic: {0}", string2);

            bool result = (new Regex(string2)).IsMatch("some/topic/bla");
            Console.WriteLine("Result: {0}", result.ToString());

            bool result2 = (new Regex("^"+string2+"$")).IsMatch("some/topic/bla");
            Console.WriteLine("Result2: {0}", result2.ToString());

            Console.ReadKey();`
`

**Mr Patierno: could you please adjust the regex matching in MqttSUbscriberManager.cs to use exact matching, as shown in above example with "bool result2"? I think this is a serious bug in GnatMQ.**

In my tests with ^$ around the regex, the wildcard replacement regexes still work as expected (just try with "string1" in the example ending in /+ or /# and you'll see) , so I think this is safe to apply this fix without breaking things. What do you think?

EDIT2 - I forked GnatMQ and tried with above modification, looks good, see https://github.com/ppatierno/gnatmq/pull/43

and, last edit, kudos to https://stackoverflow.com/questions/4581412/how-to-make-regexs-only-match-on-exact-matches for helping me finding a solution

Best regards

**Comment by dtflx01** [comment]
Hi @DennisSc,
I encountered the same issue.
Please, take a look at my correction :
In the method `public void Subscribe(string topic, byte qosLevel, MqttClient client)`
replace
`string topicReplaced = topic.Replace(PLUS_WILDCARD, PLUS_WILDCARD_REPLACE).Replace(SHARP_WILDCARD, SHARP_WILDCARD_REPLACE);`
by
`string topicReplaced = '^' + topic.Replace(PLUS_WILDCARD, PLUS_WILDCARD_REPLACE).Replace(SHARP_WILDCARD, SHARP_WILDCARD_REPLACE) + '$';`

Do the same replacement int the following method :
`public void Unsubscribe(string topic, MqttClient client)`

Regards
