### ISSUE TITLE
CPU Leak if you specify Username/password

### ISSUE THREAD

**Issue by malichishti** [gnatmq/gnatmq#49]
Hi,

Im using M2MQTT from https://www.nuget.org/packages/M2Mqtt/
IF i create a client and specify a user name the CPU usgae goes up by 25% and stays there even if the connection fails due to wrong credentials. And next call to connect will increment the CPU usage by 25%

So if you have multiple thread connecting to MQTT server, after a couple of calls the CPU reached 100% and crashes.
Following code can reproduce the issue, add it to a Console application .Net 4.5 or greater:

```
            Console.WriteLine("start?");
            Console.Read();
            Console.WriteLine("starting, please monitor the CPU usage.");
            List < MqttClient > l = new List<MqttClient>();
            for (int i = 0; i < 10; i++)
            {
                var client = new MqttClient(
                "test.mosquitto.org"
                , 1883
                , false
                , null
                , null
                , new MqttSslProtocols());
                client.MqttMsgPublishReceived += Client_MqttMsgPublishReceived;
                try
                {
                    client.Connect(Guid.NewGuid().ToString(), "ss", null);//intentionally making it fail with wrong credentials
                }
                catch(Exception ex) { Console.WriteLine("Error");  }
                l.Add(client);
            }            

            Console.WriteLine("Exit?");
            Console.Read();```

**Comment by VladimirAkopyan** [comment]
Are you using the Nuget package or compiling form source? I'd like to reproduce the issue.

**Comment by ngducnghia** [comment]
Glad you're looking into this issue @VladimirAkopyan . I'm also facing this. I use Nuget package.

**Comment by VladimirAkopyan** [comment]
@ngducnghia could you use the source from this repo and see if the issue persists? 
We've fixed quite a few bugs, but the budget wasn't updated.

**Comment by ngducnghia** [comment]
@VladimirAkopyan I couldn't build the source code because I'm using VS 2017 and there are few compatible issues. Is it possible for you to build and update the nudget?

**Comment by ngducnghia** [comment]
@VladimirAkopyan I added an SSL to project compile signing and able to resolve above SSL issue. However the issue still persists.

**Comment by GioviQ** [comment]
Sorry but this repository is about a GnatMQ a MQTT broker. Your issue is about M2Mqtt that is a client library (developed by the original developer @ppatierno of  GnatMQ) run to test.mosquitto.org that is not GnatMQ.
Please post your issue in https://github.com/eclipse/paho.mqtt.m2mqtt/issues

**Comment by ngducnghia** [comment]
@GioviQ @VladimirAkopyan I had some times this weekend to look into this issue and was able to fix it. You know well that the paho.mqtt.m2mqtt isn't active anymore. I will try to push my change there but lets me know if you want to create PR for fix here. Thanks

**Comment by GioviQ** [comment]
Hi @ngducnghia, you could make a fork of paho.mqtt.m2mqtt and commit your changes.

**Comment by ngducnghia** [comment]
@GioviQ I forked and submit PR. https://github.com/eclipse/paho.mqtt.m2mqtt/pull/79
I see the code in gnatmq client already have a check for exception. I added another check so if returnCode != CONN_ACCEPTED, it also set isRunning to false to exit the loop in ReceiveThread method.

**Comment by GioviQ** [comment]
@ngducnghia you can even just commit from Visual Studio.
