### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by GioviQ** [gnatmq/gnatmq#5]
Steps to reproduce the issue:
use MQTT.fx 0.0.16 as client and run the following script to stress the broker

var Thread = Java.type("java.lang.Thread");

function execute(action) {
    out("Test Script: " + action.getName());
    for (;;) {
    //for (var i = 0; i < 10; i++) {
        switchON();
        Thread.sleep(0);
        switchOFF();
        Thread.sleep(1);
    }
    action.setExitCode(0);
    action.setResultText("done.");
    out("Test Script: Done");
    return action;
}

function switchON() {
    out("fountain ON");
    mqttManager.publish("home/garden/fountain", "ON");
}

function switchOFF() {
    out("fountain OFF");
    mqttManager.publish("home/garden/fountain", "OFF");
}

function out(message){
     output.print(message);
}

The eventQueue keeps raising in size so memory consumption.

**Comment by dkkriste** [comment]
https://github.com/ppatierno/gnatmq/wiki/Performance

**Comment by GioviQ** [comment]
see https://github.com/ppatierno/gnatmq/issues/18

**Comment by VladimirAkopyan** [comment]
Thank you! Will give it a try asap

**Comment by dkkriste** [comment]
Btw.. i have made a quite extensive rewrite of the gnatmq project sacrificing device/IoT compatibility for performance. https://github.com/dkkriste/gnatmqforazure.git

**Comment by GioviQ** [comment]
Good to know
