### ISSUE TITLE
Exception raised when client disconnects while messages are still published

### ISSUE THREAD

**Issue by dtflx01** [gnatmq/gnatmq#51]
Hi all,
If you publish a lot of messages while a client is receiving these messages via the Broker, if the client disconnects at this time and exception is sometimes raised.
The exception is raised in the method PublishThread() file MqttPublisherManager.cs, always when processing this request :
`var query = from p in this.retainedMessages
			where (new Regex(subscriptionTopic)).IsMatch(p.Key)     // check for topics based also on wildcard with regex
			select p.Value;`
Indeed, `subscriptionTopic` becomes sometimes null processing this request.
This is happening, because `client.Close()` is called in method `CloseClient(MqttClient client)` while `PublishThread()` is processing messages on this client.

Regards

**Comment by dtflx01** [comment]
Issue similar to #22 but not the same.

**Comment by dtflx01** [comment]
See correction there : [https://github.com/dtflx01/dtflx01-gnatmq/issues/1](url)
Please merge it to master trunk.
Regards

**Comment by VladimirAkopyan** [comment]
As I've commented in a different thread, you can use your fork to submit a Pull request. I will merge as soon as you submit it.

**Comment by dtflx01** [comment]
Ok, I'll do it.
Thank you.

**Comment by VladimirAkopyan** [comment]
If this is helpfull
![image](https://user-images.githubusercontent.com/12278048/33216153-1a19cb72-d14c-11e7-8003-1da64dde116f.png)
